name: android_sip_client
description: Android-only SIP client with clean architecture

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  # Core Flutter
  flutter:
    sdk: flutter
  
  # Architecture & State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  equatable: ^2.0.5
  
  # SIP & Communication
  sip_ua:
    path: ../
  flutter_webrtc: ^0.12.6
  
  # Storage & Preferences  
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Permissions & System
  permission_handler: ^11.1.0
  
  # Background Services & Notifications
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^18.0.1
  
  # Network & Connectivity
  connectivity_plus: ^6.0.5
  
  # VPN (Android-specific)
  openvpn_flutter: ^1.3.4
  
  # Contacts & Phone
  flutter_contacts: ^1.1.9
  proximity_sensor: ^1.0.2
  
  # Audio & Vibration
  audioplayers: ^6.0.0
  vibration: ^2.0.0
  
  # Utilities
  logger: ^2.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
